# Generated by Django 6.0.2 on 2026-02-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SprintMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stream', models.CharField(choices=[('CRM', 'CRM'), ('EIP', 'EIP'), ('Website', 'Website'), ('Mobile', 'Mobile'), ('DevOps', 'DevOps'), ('SiteCore', 'SiteCore'), ('UX', 'UX')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('involved_streams', models.JSONField(default=list)),
                ('final_sp', models.FloatField(blank=True, null=True)),
                ('voting_status', models.CharField(choices=[('pending', 'Pending'), ('voting', 'Voting Open'), ('closed', 'Voting Closed')], default='pending', max_length=20)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stories', to='planner.sprintmember')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('CRM', 'CRM'), ('EIP', 'EIP'), ('Website', 'Website'), ('Mobile', 'Mobile'), ('DevOps', 'DevOps'), ('SiteCore', 'SiteCore'), ('UX', 'UX')], max_length=20)),
                ('sp', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='planner.sprintmember')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='planner.userstory')),
            ],
            options={
                'unique_together': {('user_story', 'stream', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='planner.sprintmember')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='planner.userstory')),
            ],
            options={
                'unique_together': {('user_story', 'member')},
            },
        ),
    ]
