# Generated by Django 6.0.2 on 2026-02-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sprintmember',
            name='stream',
            field=models.CharField(choices=[('CRM', 'CRM'), ('EIP', 'EIP'), ('Website', 'Website'), ('Mobile', 'Mobile'), ('DevOps', 'DevOps'), ('SiteCore', 'SiteCore'), ('UX', 'UX'), ('QA', 'QA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='streamassignment',
            name='stream',
            field=models.CharField(choices=[('CRM', 'CRM'), ('EIP', 'EIP'), ('Website', 'Website'), ('Mobile', 'Mobile'), ('DevOps', 'DevOps'), ('SiteCore', 'SiteCore'), ('UX', 'UX'), ('QA', 'QA')], max_length=20),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to='planner.sprint'),
        ),
    ]
